[package]
name = "zz_os"
version = "0.1.0"
authors = ["zz_os"]
edition = "2021"


[dependencies]
bootloader = "0.9"
volatile = "0.2.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"